<!DOCTYPE html PUBLIC 
           "-//W3C//DTD XHTML 1.0 Transitional//EN" 
           "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head>
    <meta name="verify-v1" content="qdriWngB5m+zqExgQL4Mlr6nLcPHvvNC6vaOslBWUA4=" /> 
    <meta name="description" content="Home Page of Carlos Areces" />
    <meta name="keywords" content="logic, hybrid logic, computational logics, modal logics" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

    <link rel="stylesheet" href="../../css/general.css" type="text/css" />	  
    <title>Home Page of Carlos Areces</title>
  </head>

  <body class="index">

  <a name="top"></a>

    <div class="container"><!-- Header Starts Here -->
      <div class="header">
	  <img src="../../images/menu-left.gif" alt="" width="743" height="23" />
	    <img src="../../images/links-left.gif" 
                   alt="" width="743" height="25" />
      </div>
      <!-- Header Ends Here -->
       <div class="content">
	<!--main content starts here-->

   	   <div id="rightcontent"><div class="blog">
   <div class="blogbody">
      <div class="content2">
         <h2>Resolution with Order and Selection for Hybrid Logics</h2>
         <p class="citation">Areces, C. and Gor&iacute;n, D.. Resolution with Order and Selection for Hybrid Logics. <i>Journal of Automated Reasoning</i>, 46(1):1&ndash;42, 2011.</p>
         <h4>Download: 
    <a href="files/or-full.pdf">
      [pdf]</a>&nbsp;</h4>
         <h4>Abstract: </h4>
         <p class="abstract">We investigate labeled resolution calculi for hybrid logics with inference	rules	restricted via selection functions and orders. We start by providing	a sound and refutationally	complete calculus for the hybrid logic H(@, \downarrow, A), even under	restrictions by selection	functions and orders. Then, by imposing further restrictions in the	original calculus, we	develop a sound, complete and terminating calculus for the H (@) sublanguage.	The proof	scheme we use to show refutational completeness of these calculi is	an adaptation of a	standard completeness proof for saturation-based calculi for first-order	logic that guarantees	completeness even under redundancy elimination. In fact, one of the	contributions of this	article is to show that the general framework of saturation-based	proving for first-order logic	with equality can be naturally adapted to saturation-based calculi	for other languages, in	particular modal and hybrid logics.</p>
         <h4> BibTeX: <a href="arecreso08.bib">
      (download)
     </a>
         </h4>
         <pre>@ARTICLE{arec:reso08,
  author = {Areces, C. and Gor\'{\i}n, D.},
  title = {Resolution with Order and Selection for Hybrid Logics},
  journal = {Journal of Automated Reasoning},
  year = {2011},
  volume = {46},
  pages = {1-42},
  number = {1},
  abstract = {We investigate labeled resolution calculi for hybrid logics with inference
	rules
	restricted via selection functions and orders. We start by providing
	a sound and refutationally
	complete calculus for the hybrid logic H(@, \downarrow, A), even under
	restrictions by selection
	functions and orders. Then, by imposing further restrictions in the
	original calculus, we
	develop a sound, complete and terminating calculus for the H (@) sublanguage.
	The proof
	scheme we use to show refutational completeness of these calculi is
	an adaptation of a
	standard completeness proof for saturation-based calculi for first-order
	logic that guarantees
	completeness even under redundancy elimination. In fact, one of the
	contributions of this
	article is to show that the general framework of saturation-based
	proving for first-order logic
	with equality can be naturally adapted to saturation-based calculi
	for other languages, in
	particular modal and hybrid logics.},
  bibsource = {DBLP, http://dblp.uni-trier.de},
  ee = {http://dx.doi.org/10.1007/s10817-010-9167-0}
}
</pre>
      </div>
      <hr width="100%" size="2"/>
      <p>
         <small>
 Generated by
 <a href="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html">bib2html.pl</a>
 (written by <a href="http://www.cs.cmu.edu/~pfr">Patrick Riley</a>) on
  Sun Oct 02, 2016 17:05:49</small>
      </p>
   </div>
</div>
<div id="copyright">
             <br />


<hr width="100%" size="-2"  />

<div style="text-align:right; font-size:xx-small; padding-bottom: 3px;">
&copy; 2004 Maintained by Carlos Areces. Last updated: 01-07-2019.
</div>

          </div>

        </div><!--rightcontent-->
      <!-- Leftcontent Starts Here -->
      <div class="leftcontent">
	    <center>
	        <a href="http://www.cs.famaf.unc.edu.ar/~careces"><img src="../../images/carlos.jpg" alt= "[ -Myself- ]"/></a>
        </center>
        <center>
            <a class="side" href="../../content/whoiam.php">Who I am</a>
	    </center>
	
	    <!-- Leftmenu Start Here -->
	    <div class="leftmenu">
	        <div class="sidetitle">Academic</div>
   	            <a class="side" href="http://liis.famaf.unc.edu.ar/">My Research Group</a><br />
                <a class="side" href="../../content/papers/sort_date.php">My Papers</a><br />
              
            <div class="sidetitle">Things I'm doing</div>
                <a class="side" href="../../infinis.php">INFINIS</a><br />
                <a class="side" href="http://www.meals-project.eu/">MEALS</a><br />
                <a class="side" href="http://hylo.loria.fr">Hybrid Logics Web Page</a><br />
                <a class="side" href="http://www.cs.famaf.unc.edu.ar/~careces/M4M">Methods for Modalities</a><br />
                
            <div class="sidetitle">Courses</div>
                <a class="side" href="http://cs.famaf.unc.edu.ar/~careces/ml18">Modal Logics @ Stanford</a><br />
                <a class="side" href="http://www.famaf.proed.unc.edu.ar/course/view.php?id=12">introalg</a><br />
                <a class="side" href="http://cs.famaf.unc.edu.ar/~careces/lm17">L&oacute;gicas Modales</a><br />
                <a class="side" href="../../content/courses.php">Old Courses</a><br />

	    </div>
	    <!-- Leftmenu Ends Here -->
	    <br />
	</div>
    <!-- Leftcontent Ends Here -->   </div>
<p>
&nbsp;<br />
</p>
    </div>

  </body>
</html>