<!DOCTYPE html PUBLIC 
           "-//W3C//DTD XHTML 1.0 Transitional//EN" 
           "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head>
    <meta name="verify-v1" content="qdriWngB5m+zqExgQL4Mlr6nLcPHvvNC6vaOslBWUA4=" /> 
    <meta name="description" content="Home Page of Carlos Areces" />
    <meta name="keywords" content="logic, hybrid logic, computational logics, modal logics" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

    <link rel="stylesheet" href="../../css/general.css" type="text/css" />	  
    <title>Home Page of Carlos Areces</title>
  </head>

  <body class="index">

  <a name="top"></a>

    <div class="container"><!-- Header Starts Here -->
      <div class="header">
	  <img src="../../images/menu-left.gif" alt="" width="743" height="23" />
	    <img src="../../images/links-left.gif" 
                   alt="" width="743" height="25" />
      </div>
      <!-- Header Ends Here -->
       <div class="content">
	<!--main content starts here-->

   	   <div id="rightcontent"><div class="blog">
   <div class="blogbody">
      <div class="content2">
         <h2>Keys, Nominals, and Concrete Domains</h2>
         <p class="citation">Lutz, C., Areces, C., Horrocks, I., and Sattler, U.. Keys, Nominals, and Concrete Domains. <i>Journal of Artificial Intelligence Research</i>, 23:667&ndash;726, 2004.</p>
         <h4>Download: 
    <a href="files/lutz05a.pdf">
      [pdf]</a>&nbsp;</h4>
         <h4>Abstract: </h4>
         <p class="abstract">Many description logics (DLs) combine knowledge representation on	an abstract, logical level with an interface to 'concrete' domains	like numbers and strings with built-in predicates such as &gt;, +, and	prefix-of. These hybrid DLs have turned out to be useful in several	application areas, such as reasoning about conceptual database models.	We propose to further extend such DLs with key constraints that allow	the expression of statements like 'US citizens are uniquely identified	by their social security number'. Based on this idea, we introduce	a number of natural description logics and perform a detailed analysis	of their decidability and computational complexity. It turns out	that naive extensions with key constraints easily lead to undecidability,	whereas more careful extensions yield NExpTime-complete DLs for a	variety of useful concrete domains. </p>
         <h4> BibTeX: <a href="lutzkeys04.bib">
      (download)
     </a>
         </h4>
         <pre>@ARTICLE{lutz:keys04,
  author = {Lutz, C. and Areces, C. and Horrocks, I. and Sattler, U.},
  title = {Keys, Nominals, and Concrete Domains},
  journal = {Journal of Artificial Intelligence Research},
  year = {2004},
  volume = {23},
  pages = {667--726},
  abstract = {Many description logics (DLs) combine knowledge representation on
	an abstract, logical level with an interface to 'concrete' domains
	like numbers and strings with built-in predicates such as &gt;, +, and
	prefix-of. These hybrid DLs have turned out to be useful in several
	application areas, such as reasoning about conceptual database models.
	We propose to further extend such DLs with key constraints that allow
	the expression of statements like 'US citizens are uniquely identified
	by their social security number'. Based on this idea, we introduce
	a number of natural description logics and perform a detailed analysis
	of their decidability and computational complexity. It turns out
	that naive extensions with key constraints easily lead to undecidability,
	whereas more careful extensions yield NExpTime-complete DLs for a
	variety of useful concrete domains. },
}
</pre>
      </div>
      <hr width="100%" size="2"/>
      <p>
         <small>
 Generated by
 <a href="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html">bib2html.pl</a>
 (written by <a href="http://www.cs.cmu.edu/~pfr">Patrick Riley</a>) on
  Sun Oct 02, 2016 17:05:49</small>
      </p>
   </div>
</div>
<div id="copyright">
             <br />


<hr width="100%" size="-2"  />

<div style="text-align:right; font-size:xx-small; padding-bottom: 3px;">
&copy; 2004 Maintained by Carlos Areces. Last updated: 01-07-2019.
</div>

          </div>

        </div><!--rightcontent-->
      <!-- Leftcontent Starts Here -->
      <div class="leftcontent">
	    <center>
	        <a href="http://www.cs.famaf.unc.edu.ar/~careces"><img src="../../images/carlos.jpg" alt= "[ -Myself- ]"/></a>
        </center>
        <center>
            <a class="side" href="../../content/whoiam.php">Who I am</a>
	    </center>
	
	    <!-- Leftmenu Start Here -->
	    <div class="leftmenu">
	        <div class="sidetitle">Academic</div>
   	            <a class="side" href="http://liis.famaf.unc.edu.ar/">My Research Group</a><br />
                <a class="side" href="../../content/papers/sort_date.php">My Papers</a><br />
              
            <div class="sidetitle">Things I'm doing</div>
                <a class="side" href="../../infinis.php">INFINIS</a><br />
                <a class="side" href="http://www.meals-project.eu/">MEALS</a><br />
                <a class="side" href="http://hylo.loria.fr">Hybrid Logics Web Page</a><br />
                <a class="side" href="http://www.cs.famaf.unc.edu.ar/~careces/M4M">Methods for Modalities</a><br />
                
            <div class="sidetitle">Courses</div>
                <a class="side" href="http://cs.famaf.unc.edu.ar/~careces/ml18">Modal Logics @ Stanford</a><br />
                <a class="side" href="http://www.famaf.proed.unc.edu.ar/course/view.php?id=12">introalg</a><br />
                <a class="side" href="http://cs.famaf.unc.edu.ar/~careces/lm17">L&oacute;gicas Modales</a><br />
                <a class="side" href="../../content/courses.php">Old Courses</a><br />

	    </div>
	    <!-- Leftmenu Ends Here -->
	    <br />
	</div>
    <!-- Leftcontent Ends Here -->   </div>
<p>
&nbsp;<br />
</p>
    </div>

  </body>
</html>