<!DOCTYPE html PUBLIC 
           "-//W3C//DTD XHTML 1.0 Transitional//EN" 
           "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head>
    <meta name="verify-v1" content="qdriWngB5m+zqExgQL4Mlr6nLcPHvvNC6vaOslBWUA4=" /> 
    <meta name="description" content="Home Page of Carlos Areces" />
    <meta name="keywords" content="logic, hybrid logic, computational logics, modal logics" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

    <link rel="stylesheet" href="../../css/general.css" type="text/css" />	  
    <title>Home Page of Carlos Areces</title>
  </head>

  <body class="index">

  <a name="top"></a>

    <div class="container"><!-- Header Starts Here -->
      <div class="header">
	  <img src="../../images/menu-left.gif" alt="" width="743" height="23" />
	    <img src="../../images/links-left.gif" 
                   alt="" width="743" height="25" />
      </div>
      <!-- Header Ends Here -->
       <div class="content">
	<!--main content starts here-->

   	   <div id="rightcontent"><div class="blog">
   <div class="blogbody">
      <div class="content2">
         <h2>Characterization Results for d-Horn Formulas</h2>
         <p class="citation">Areces, C., Becher, V., and Ferro, S.. Characterization Results for d-Horn Formulas. In Cavedon, L., Blackburn, P., Braisby, N., and Shimojima, A., editors, <i>Logic, Language and Computation</i>, pp. 49&ndash;66, CSLI Publications, 2000. Extended version of ``Characterization Results for d-Horn Formulas''	(Areces, Becher and Ferro).</p>
         <h4>Download: 
    <a href="files/d-horn.pdf">
      [pdf]</a>&nbsp;</h4>
         <h4>Abstract: </h4>
         <p class="abstract">We provide two different model theoretic characterizations of a fragment	of first-order logic which we call d-Horn formulas. This fragment	is dual to the well known Horn fragment and has the same complexity	for proving unsatisfiability. The method used in the characterization	(syntactic translation functions between formulas which are mimicked	by translation functions between models) might be applied to characterize	other first-order restrictions. This paper is related to the work	of Henschen and Wos \shortcitehens:unit74, but we study semantic	translation together with syntactic renaming functions. We comment	shortly on a number of applications of d-Horn formulas, one of which	is the characterization of Context Free Grammars through a Horn $\cup$	d-Horn first-order theory.</p>
         <h4> BibTeX: <a href="arecchar00.bib">
      (download)
     </a>
         </h4>
         <pre>@INCOLLECTION{arec:char00,
  author = {Areces, C. and Becher, V. and Ferro, S.},
  title = {Characterization Results for d-{H}orn Formulas},
  booktitle = {Logic, Language and Computation},
  publisher = {CSLI Publications},
  year = {2000},
  editor = {Cavedon, L. and Blackburn, P. and Braisby, N. and Shimojima, A.},
  volume = {3},
  pages = {49--66},
  note = {Extended version of ``Characterization Results for d-{H}orn Formulas''
	(Areces, Becher and Ferro).},
  abstract = {We provide two different model theoretic characterizations of a fragment
	of first-order logic which we call d-Horn formulas. This fragment
	is dual to the well known Horn fragment and has the same complexity
	for proving unsatisfiability. The method used in the characterization
	(syntactic translation functions between formulas which are mimicked
	by translation functions between models) might be applied to characterize
	other first-order restrictions. This paper is related to the work
	of Henschen and Wos \shortcite{hens:unit74}, but we study semantic
	translation together with syntactic renaming functions. We comment
	shortly on a number of applications of d-Horn formulas, one of which
	is the characterization of Context Free Grammars through a Horn $\cup$
	d-Horn first-order theory.},
}
</pre>
      </div>
      <hr width="100%" size="2"/>
      <p>
         <small>
 Generated by
 <a href="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html">bib2html.pl</a>
 (written by <a href="http://www.cs.cmu.edu/~pfr">Patrick Riley</a>) on
  Sun Oct 02, 2016 17:05:49</small>
      </p>
   </div>
</div>
<div id="copyright">
             <br />


<hr width="100%" size="-2"  />

<div style="text-align:right; font-size:xx-small; padding-bottom: 3px;">
&copy; 2004 Maintained by Carlos Areces. Last updated: 01-07-2019.
</div>

          </div>

        </div><!--rightcontent-->
      <!-- Leftcontent Starts Here -->
      <div class="leftcontent">
	    <center>
	        <a href="http://www.cs.famaf.unc.edu.ar/~careces"><img src="../../images/carlos.jpg" alt= "[ -Myself- ]"/></a>
        </center>
        <center>
            <a class="side" href="../../content/whoiam.php">Who I am</a>
	    </center>
	
	    <!-- Leftmenu Start Here -->
	    <div class="leftmenu">
	        <div class="sidetitle">Academic</div>
   	            <a class="side" href="http://liis.famaf.unc.edu.ar/">My Research Group</a><br />
                <a class="side" href="../../content/papers/sort_date.php">My Papers</a><br />
              
            <div class="sidetitle">Things I'm doing</div>
                <a class="side" href="../../infinis.php">INFINIS</a><br />
                <a class="side" href="http://www.meals-project.eu/">MEALS</a><br />
                <a class="side" href="http://hylo.loria.fr">Hybrid Logics Web Page</a><br />
                <a class="side" href="http://www.cs.famaf.unc.edu.ar/~careces/M4M">Methods for Modalities</a><br />
                
            <div class="sidetitle">Courses</div>
                <a class="side" href="http://cs.famaf.unc.edu.ar/~careces/ml18">Modal Logics @ Stanford</a><br />
                <a class="side" href="http://www.famaf.proed.unc.edu.ar/course/view.php?id=12">introalg</a><br />
                <a class="side" href="http://cs.famaf.unc.edu.ar/~careces/lm17">L&oacute;gicas Modales</a><br />
                <a class="side" href="../../content/courses.php">Old Courses</a><br />

	    </div>
	    <!-- Leftmenu Ends Here -->
	    <br />
	</div>
    <!-- Leftcontent Ends Here -->   </div>
<p>
&nbsp;<br />
</p>
    </div>

  </body>
</html>