<!DOCTYPE html PUBLIC 
           "-//W3C//DTD XHTML 1.0 Transitional//EN" 
           "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head>
    <meta name="verify-v1" content="qdriWngB5m+zqExgQL4Mlr6nLcPHvvNC6vaOslBWUA4=" /> 
    <meta name="description" content="Home Page of Carlos Areces" />
    <meta name="keywords" content="logic, hybrid logic, computational logics, modal logics" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

    <link rel="stylesheet" href="../../css/general.css" type="text/css" />	  
    <title>Home Page of Carlos Areces</title>
  </head>

  <body class="index">

  <a name="top"></a>

    <div class="container"><!-- Header Starts Here -->
      <div class="header">
	  <img src="../../images/menu-left.gif" alt="" width="743" height="23" />
	    <img src="../../images/links-left.gif" 
                   alt="" width="743" height="25" />
      </div>
      <!-- Header Ends Here -->
       <div class="content">
	<!--main content starts here-->

   	   <div id="rightcontent"><div class="blog">
   <div class="blogbody">
      <div class="content2">
         <h2>Failure of interpolation in combined modal logics</h2>
         <p class="citation">Marx, M. and Areces, C.. Failure of interpolation in combined modal logics. <i>Notre Dame Journal of Formal Logic</i>, 39(2):253&ndash;273, 1998.</p>
         <h4>Download: 
    <a href="files/failure.pdf">
      [pdf]</a>&nbsp;</h4>
         <h4>Abstract: </h4>
         <p class="abstract">We investigate transfer of interpolation in such combinations of modal	logic which lead to interaction of the modalities. Combining logics	by taking products often blocks transfer of interpolation. The same	holds for combinations by taking unions, a generalization of Humberstone's	inaccessibility logic. Viewing first order logic as a product of	modal logics, we derive a strong counterexample for failure of interpolation	in the finite variable fragments of first order logic. We provide	a simple condition stated only in terms of frames and bisimulations	which implies failure of interpolation. Its use is exemplified in	a wide range of cases.</p>
         <h4> BibTeX: <a href="arecfail98.bib">
      (download)
     </a>
         </h4>
         <pre>@ARTICLE{arec:fail98,
  author = {Marx, M. and Areces, C.},
  title = {Failure of interpolation in combined modal logics},
  journal = {Notre Dame Journal of Formal Logic},
  year = {1998},
  volume = {39},
  pages = {253--273},
  number = {2},
  abstract = {We investigate transfer of interpolation in such combinations of modal
	logic which lead to interaction of the modalities. Combining logics
	by taking products often blocks transfer of interpolation. The same
	holds for combinations by taking unions, a generalization of Humberstone's
	inaccessibility logic. Viewing first order logic as a product of
	modal logics, we derive a strong counterexample for failure of interpolation
	in the finite variable fragments of first order logic. We provide
	a simple condition stated only in terms of frames and bisimulations
	which implies failure of interpolation. Its use is exemplified in
	a wide range of cases.},
}
</pre>
      </div>
      <hr width="100%" size="2"/>
      <p>
         <small>
 Generated by
 <a href="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html">bib2html.pl</a>
 (written by <a href="http://www.cs.cmu.edu/~pfr">Patrick Riley</a>) on
  Sun Oct 02, 2016 17:05:49</small>
      </p>
   </div>
</div>
<div id="copyright">
             <br />


<hr width="100%" size="-2"  />

<div style="text-align:right; font-size:xx-small; padding-bottom: 3px;">
&copy; 2004 Maintained by Carlos Areces. Last updated: 01-07-2019.
</div>

          </div>

        </div><!--rightcontent-->
      <!-- Leftcontent Starts Here -->
      <div class="leftcontent">
	    <center>
	        <a href="http://www.cs.famaf.unc.edu.ar/~careces"><img src="../../images/carlos.jpg" alt= "[ -Myself- ]"/></a>
        </center>
        <center>
            <a class="side" href="../../content/whoiam.php">Who I am</a>
	    </center>
	
	    <!-- Leftmenu Start Here -->
	    <div class="leftmenu">
	        <div class="sidetitle">Academic</div>
   	            <a class="side" href="http://liis.famaf.unc.edu.ar/">My Research Group</a><br />
                <a class="side" href="../../content/papers/sort_date.php">My Papers</a><br />
              
            <div class="sidetitle">Things I'm doing</div>
                <a class="side" href="../../infinis.php">INFINIS</a><br />
                <a class="side" href="http://www.meals-project.eu/">MEALS</a><br />
                <a class="side" href="http://hylo.loria.fr">Hybrid Logics Web Page</a><br />
                <a class="side" href="http://www.cs.famaf.unc.edu.ar/~careces/M4M">Methods for Modalities</a><br />
                
            <div class="sidetitle">Courses</div>
                <a class="side" href="http://cs.famaf.unc.edu.ar/~careces/ml18">Modal Logics @ Stanford</a><br />
                <a class="side" href="http://www.famaf.proed.unc.edu.ar/course/view.php?id=12">introalg</a><br />
                <a class="side" href="http://cs.famaf.unc.edu.ar/~careces/lm17">L&oacute;gicas Modales</a><br />
                <a class="side" href="../../content/courses.php">Old Courses</a><br />

	    </div>
	    <!-- Leftmenu Ends Here -->
	    <br />
	</div>
    <!-- Leftcontent Ends Here -->   </div>
<p>
&nbsp;<br />
</p>
    </div>

  </body>
</html>